select
round(count_10.cnt*1.0/countAll.cnt, 3) as '-1.0 to -0.9',
round(count_9.cnt*1.0/countAll.cnt, 3)  as '-0.9 to -0.8',
round(count_8.cnt*1.0/countAll.cnt, 3)  as '-0.8 to -0.7',
round(count_7.cnt*1.0/countAll.cnt, 3)  as '-0.7 to -0.6',
round(count_6.cnt*1.0/countAll.cnt, 3)  as '-0.6 to -0.5',
round(count_5.cnt*1.0/countAll.cnt, 3)  as '-0.5 to -0.4',
round(count_4.cnt*1.0/countAll.cnt, 3)  as '-0.4 to -0.3',
round(count_3.cnt*1.0/countAll.cnt, 3)  as '-0.3 to -0.2',
round(count_2.cnt*1.0/countAll.cnt, 3)  as '-0.2 to -0.1',
round(count_1.cnt*1.0/countAll.cnt, 3)  as '-0.1 to  0.0',
round(count1.cnt*1.0/countAll.cnt, 3)   as ' 0.0 to  0.1',
round(count2.cnt*1.0/countAll.cnt, 3)   as ' 0.1 to  0.2',
round(count3.cnt*1.0/countAll.cnt, 3)   as ' 0.2 to  0.3',
round(count4.cnt*1.0/countAll.cnt, 3)   as ' 0.3 to  0.4',
round(count5.cnt*1.0/countAll.cnt, 3)   as ' 0.4 to  0.5',
round(count6.cnt*1.0/countAll.cnt, 3)   as ' 0.5 to  0.6',
round(count7.cnt*1.0/countAll.cnt, 3)   as ' 0.6 to  0.7',
round(count8.cnt*1.0/countAll.cnt, 3)   as ' 0.7 to  0.8',
round(count9.cnt*1.0/countAll.cnt, 3)   as ' 0.8 to  0.9',
round(count10.cnt*1.0/countAll.cnt, 3)  as ' 0.9 to  1.0'
from
(select count(*) as cnt from Similarities) as countAll,
(select count(*) as cnt from Similarities where CosineSim > -1.0 and CosineSim <= -0.9) as count_10,
(select count(*) as cnt from Similarities where CosineSim > -0.9 and CosineSim <= -0.8) as count_9,
(select count(*) as cnt from Similarities where CosineSim > -0.8 and CosineSim <= -0.7) as count_8,
(select count(*) as cnt from Similarities where CosineSim > -0.7 and CosineSim <= -0.6) as count_7,
(select count(*) as cnt from Similarities where CosineSim > -0.6 and CosineSim <= -0.5) as count_6,
(select count(*) as cnt from Similarities where CosineSim > -0.5 and CosineSim <= -0.4) as count_5,
(select count(*) as cnt from Similarities where CosineSim > -0.4 and CosineSim <= -0.3) as count_4,
(select count(*) as cnt from Similarities where CosineSim > -0.3 and CosineSim <= -0.2) as count_3,
(select count(*) as cnt from Similarities where CosineSim > -0.2 and CosineSim <= -0.1) as count_2,
(select count(*) as cnt from Similarities where CosineSim > -0.1 and CosineSim <= 0.0) as count_1,
(select count(*) as cnt from Similarities where CosineSim > 0.0 and CosineSim <= 0.1) as count1,
(select count(*) as cnt from Similarities where CosineSim > 0.1 and CosineSim <= 0.2) as count2,
(select count(*) as cnt from Similarities where CosineSim > 0.2 and CosineSim <= 0.3) as count3,
(select count(*) as cnt from Similarities where CosineSim > 0.3 and CosineSim <= 0.4) as count4,
(select count(*) as cnt from Similarities where CosineSim > 0.4 and CosineSim <= 0.5) as count5,
(select count(*) as cnt from Similarities where CosineSim > 0.5 and CosineSim <= 0.6) as count6,
(select count(*) as cnt from Similarities where CosineSim > 0.6 and CosineSim <= 0.7) as count7,
(select count(*) as cnt from Similarities where CosineSim > 0.7 and CosineSim <= 0.8) as count8,
(select count(*) as cnt from Similarities where CosineSim > 0.8 and CosineSim <= 0.9) as count9,
(select count(*) as cnt from Similarities where CosineSim > 0.9 and CosineSim <= 1.0) as count10
;
